development:
  adapter: postgresql
  database: arepa_development
  pool: 5
  timeout: 5000

test:
  adapter: postgresql
  database: arepa_test
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: production
  pool: 5
  timeout: 5000